### ISSUE TITLE
ImageCore breaks Gadfly

### ISSUE THREAD

**Issue by NicholasWMRitchie** [JuliaImages/ImageCore.jl#150]
It seems that recent changes to ImageCore.jl has broken Gadfly.ManualDiscreteKey (manual_discrete_key(....) and manual_color_key(...)).  The key line is `convert(::Type{Array{ColorTypes.Color,N} where N}, ::Array{ColorTypes.Color,1})@deprecations.jl:62` which is in ImageCore.jl and seems to be one of these dreaded invalidations.
    
    Failed to show value:

    MethodError: no method matching ColorTypes.Color(::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}})

    _broadcast_getindex_evalf@broadcast.jl:648[inlined]
    _broadcast_getindex@broadcast.jl:621[inlined]
    getindex@broadcast.jl:575[inlined]
    copy@broadcast.jl:876[inlined]
    materialize@broadcast.jl:837[inlined]
    convert(::Type{Array{ColorTypes.Color,N} where N}, ::Array{ColorTypes.Color,1})@deprecations.jl:62
    cat_aes_var!(::IndirectArrays.IndirectArray{ColorTypes.Color,1,Array{Int64,1},Array{ColorTypes.Color,1}}, ::IndirectArrays.IndirectArray{ColorTypes.Color,1,Array{Int64,1},Array{ColorTypes.Color,1}})@aesthetics.jl:300
    concat(::Gadfly.Aesthetics, ::Vararg{Gadfly.Aesthetics,N} where N)@aesthetics.jl:250
    render_prepare(::Gadfly.Plot)@Gadfly.jl:685
    render(::Gadfly.Plot)@Gadfly.jl:740
    draw@Gadfly.jl:847[inlined]
    show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("text/html")}, ::Gadfly.Plot)@Gadfly.jl:937
    #show_richest#18(::Bool, ::typeof(Main.PlutoRunner.show_richest), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:382
    show_richest(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:330
    #sprint_withreturned#17(::IOContext{Base.PipeEndpoint}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::Gadfly.Plot)@PlutoRunner.jl:302
    format_output(::Any)@PlutoRunner.jl:242
    formatted_result_of(::Base.UUID, ::Bool)@PlutoRunner.jl:53
    top-level scope@none:1 in ImageCore.jl and seems to be one of these dreaded invalidations.

I don't know if Gadfly or ImageCore needs to fix this so I submitted to both. (https://github.com/GiovineItalia/Gadfly.jl/issues/1466)

**Comment by timholy** [comment]
Might be a good chance to delete [those depwarns](https://github.com/JuliaImages/ImageCore.jl/blob/master/src/deprecations.jl) and release a new minor version. Can you test whether that fixes Gadfly?

**Comment by ViralBShah** [comment]
Can this one be closed?

**Comment by NicholasWMRitchie** [comment]
Yes, I ran the code that initially produced the error (https://github.com/GiovineItalia/Gadfly.jl/issues/1466) and it now works fine.
