### ISSUE TITLE
Views documentation outdated?

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageCore.jl#17]
I noticed that the documentation for Views (https://juliaimages.github.io/ImageCore.jl/latest/views.html#Views-1) shows code snippets that yield a output that is different from what really happens (for me anyways).
What I mean is that the code snippets for `channelview` and `rawview` end up simply reinterpreting the original plain array `img` and not decorating it in a `ChannelView` as the documentation claims.

Is this on purpose for the sake of clarity? I guess there is a case to be made that it would look weird to start the page with creating a sub-array just to prevent `reinterpret`.
If it is just outdated I could update it in a PR if you want.

**Comment by timholy** [comment]
No, the documentation is in flux right now. I already have it updated locally. Soon there might be another mismatch depending on whether you are working with https://github.com/JuliaMath/FixedPointNumbers.jl/pull/51 "installed" or not; I'm going to rewrite the documentation with it, in hopes of encouraging folks to try it and see what they think.

I am _certain_, like I never have been before, that by the end of the weekend there will be instructions about how to test all this new stuff out (with instructions about which branches of which packages to check out to ensure a consistent experience).

**Comment by timholy** [comment]
Oh, and pushing the new documentation here is waiting on https://github.com/JuliaLang/METADATA.jl/pull/6753. Other related issues: https://github.com/JuliaDocs/Documenter.jl/issues/319.

**Comment by Evizero** [comment]
I see. Thanks. Sorry for the noise then. I guess I am just eager to catch up

**Comment by timholy** [comment]
I am eager to have this out (and to be done with it). It's been a long slog.
