### ISSUE TITLE
calling colorview with AlphaColor yields unexpected result

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageCore.jl#25]
I get some (to me) surprising inconsistencies when using `colorview` with an `AlphaColor`

```julia
julia> using ColorTypes, FixedPointNumbers, ImageCore

julia> x = zeros(N0f8,2,2,2);

julia> x[1,:,:] = N0f8[0. 0.3; 0.7 1]
2×2 Array{N0f8,2}:
 0.0N0f8    0.298N0f8
 0.698N0f8  1.0N0f8  

julia> x[2,:,:] = N0f8[1. 0.7; 0.3 0.]
2×2 Array{N0f8,2}:
 1.0N0f8    0.698N0f8
 0.298N0f8  0.0N0f8  

julia> colorview(AGray, x)
2×2 ColorView{AGray}(::Array{N0f8,3}) with element type ColorTypes.AGray{FixedPointNumbers.Normed{UInt8,8}}:
 AGray{N0f8}(0.0,1.0)      AGray{N0f8}(0.298,0.698)
 AGray{N0f8}(0.698,0.298)  AGray{N0f8}(1.0,0.0)    

julia> reinterpret(AGray, x)
2×2 Array{AGray{N0f8},2}:
 AGray{N0f8}(1.0,0.0)      AGray{N0f8}(0.698,0.298)
 AGray{N0f8}(0.298,0.698)  AGray{N0f8}(0.0,1.0)
```

Two things I found surprising.

1. That `colorview` returns a `ColorView` instead of doing a `reinterpret`.
2. That `reinterpret` returns a different result than colorview.

Since it is an `AlphaColor`, the result of `reinterpret` shown above is to me the expected result

It is interesting that the invoked method of `colorview` seems to be https://github.com/JuliaImages/ImageCore.jl/blob/master/src/colorchannels.jl#L255, which looks like the most general fallback method. Since `ColorAlpha` gets special treatment, maybe `AlphaColor` should as well?

Is this a feature or a bug?

**Comment by timholy** [comment]
Perhaps surprisingly, it's a feature. (One that might need more documentation? Please check.) 
```julia
julia> using ColorTypes

julia> alpha(GrayA(0.2, 0.8))
0.8

julia> alpha(AGray(0.2, 0.8))
0.8
```
The core principle is that the API should be uniform (e.g., alpha is always last) and that the internal storage is a detail that users shouldn't worry about. This is particularly important for types like `RGB1` and `RGB4` (where there's a dummy byte you'd rather not have to deal with), but it's useful for many types. Otherwise you'd have to have more specializations depending on storage order than we have now.

`colorview` gives the same result as calling the `Colorant` constructor on columns of the array. That's also why it's returning a `ColorView` and not just an `Array`, because as you noted you can't get that result from `reinterpret`.

**Comment by timholy** [comment]
In general, unless you have an explicit need (e.g., iterop with a C library), it's probably less confusing to use types like `RGBA` and `GrayA` than `ARGB` and `AGray`. The diversity of types is partially designed for interop with libraries like OpenGL.

**Comment by Evizero** [comment]
> colorview gives the same result as calling the Colorant constructor on columns of the array.

That sentence explains it all, really. This would be a helpful statement to make in the docstring. 

I was aware of the `Colorant` constructors, but in my mind I thought `colorview` was intended to be something of a lazy `reinterpret` for when `reinterpret` wasn't possible. Now that I think of it in the new light, I am unsure how I came to this conclusion. Maybe because it makes use of `reinterpret` in a lot of cases it made it look to me as it was the functionality to emulate for `AbstractArray`s.

Thanks for clearing this up

**Comment by timholy** [comment]
Check the docstring for `ColorView` (separate from `colorview`). Is that good enough, should we duplicate the information in `colorview`, or is even more information necessary?

**Comment by Evizero** [comment]
Oh interesting. I'll admit I only ever looked at `colorview` in my confusion.

> Of relevance for types like RGB and BGR, the elements of A are interpreted in constructor-argument order, not memory order (see reinterpret if you want to use memory order).

This sentence seems copy worthy to `colorview`. But I think it is good enough as it is. I went into this issue with a strong bias to begin with
