### ISSUE TITLE
What's the new way to autoscale?

### ISSUE THREAD

**Issue by rsrock** [JuliaImages/ImageCore.jl#29]
I'm looking for a replacement for `ScaleAutoMinMax`.  Is the best way to do this `f = takemap(scaleminmax, img)`, and then broadcast over the `img`?  Or, in my case, `Gray.(f.(img))` to get a gray image?

[edit] I see that `f = takemap(scaleminmax, Gray, img); f.(img)` also works, but I'm looking for a shortcut.

**Comment by timholy** [comment]
It wouldn't be unreasonable to hope that `Gray.(scaleminmax(img))` should do what want. Not quite sure what to do about the two senses of `scaleminmax`, however. Any ideas?

**Comment by johnnychen94** [comment]
I find `clamp` and `clamp01` works for your case. However, it doesn't support linear transform.

**Comment by johnnychen94** [comment]
Now we're using `adjust_histogram` from `ImageContrastAdjustment`

```julia
adjust_histogram(img, LinearStretching())
```
