### ISSUE TITLE
`reinterpret(::Colorant)` gives incorrect size for vector input after loading ImageCore

### ISSUE THREAD

**Issue by rdeits** [JuliaImages/ImageCore.jl#33]
Moved from https://github.com/JuliaImages/Images.jl/issues/621

ImageCore seems to be performing some type-piracy, with the result that `reinterpret()` starts producing the wrong output size for Colorant types after this package is loaded:

```julia
julia> using Colors, FixedPointNumbers

julia> reinterpret(BGRA{N0f8}, [0xf0884422])
1-element Array{ColorTypes.BGRA{FixedPointNumbers.Normed{UInt8,8}},1}:
 BGRA{N0f8}(0.533,0.267,0.133,0.941)

julia> import ImageCore

julia> reinterpret(BGRA{N0f8}, [0xf0884422])
0-dimensional Array{BGRA{N0f8},0}:
BGRA{N0f8}(0.533,0.267,0.133,0.941)
```

This is the root cause of the test failures in https://github.com/JuliaIO/ImageMagick.jl/pull/84

**Comment by rdeits** [comment]
This in turn happens because `ImageCore.reinterpret()` ultimately calls:

```julia
function _reinterpret_array_cv{T,CV<:Colorant}(::Type{CV}, A::Array{T})
    reinterpret(CV, A, tail(size(A)))
end
```

and `Base.tail((1,))` is just the empty tuple. 

Is the idea behind these `reinterpret` overloads to allow an C x M x N array to be converted into an M x N image? In that case, maybe https://github.com/JuliaImages/ImageCore.jl/blob/master/src/convert_reinterpret.jl#L30 should be changed to not invoke that behavior?

**Comment by timholy** [comment]
Yes, you've diagnosed the problem correctly. Maybe we shouldn't eat a dimension for 1d inputs.

Here are some other interesting failures when ImageCore is loaded:
```julia
julia> using Colors, FixedPointNumbers, ImageCore

julia> reinterpret(BGRA{N0f8}, rand(UInt32, 5, 5))
ERROR: DimensionMismatch("new dimensions (5,) must be consistent with array size 25")
 in reinterpret(::Type{ColorTypes.BGRA{FixedPointNumbers.Normed{UInt8,8}}}, ::Array{UInt32,2}, ::Tuple{Int64}) at ./array.jl:94
 in reinterpret(::Type{ColorTypes.BGRA{FixedPointNumbers.Normed{UInt8,8}}}, ::Array{UInt32,2}) at /home/tim/.julia/v0.5/ImageCore/src/convert_reinterpret.jl:31

julia> reinterpret(BGRA{N0f8}, [0x22, 0x44, 0x88, 0xf0, 0x01, 0x02, 0x03, 0x04])
ERROR: DimensionMismatch("new dimensions () must be consistent with array size 2")
 in reinterpret(::Type{ColorTypes.BGRA{FixedPointNumbers.Normed{UInt8,8}}}, ::Array{UInt8,1}, ::Tuple{}) at ./array.jl:94
 in reinterpret(::Type{ColorTypes.BGRA{FixedPointNumbers.Normed{UInt8,8}}}, ::Array{UInt8,1}) at /home/tim/.julia/v0.5/ImageCore/src/convert_reinterpret.jl:30
```
