### ISSUE TITLE
convert ambiguity error

### ISSUE THREAD

**Issue by marius311** [JuliaImages/ImageCore.jl#40]
I'm getting the following. 

```
MethodError: convert(::Type{Array{Union{},1}}, ::Array{Union{},1}) is ambiguous. Candidates:
  convert(::Type{Array{Cdest,n}}, img::AbstractArray{T,n}) where {Cdest<:(ColorTypes.Colorant{T,1} where T), n, T<:Real} in ImageCore at /home/marius/.julia/v0.6/ImageCore/src/convert_reinterpret.jl:105
  convert(::Type{Array{C,n}}, img::Array{C,n}) where {C<:ColorTypes.Colorant, n} in ImageCore at /home/marius/.julia/v0.6/ImageCore/src/convert_reinterpret.jl:76
Possible fix, define
  convert(::Type{Array{Union{},n}}, ::Array{Union{},n})
```

I unfortunately don't have a code snippet to trigger this, its coming from some comprehension and I can't actually figure out what triggers the call to convert, nevertheless, there is the ambiguity error. 

```
julia> versioninfo()
Julia Version 0.6.0-rc1.0
Commit 6bdb395* (2017-05-07 00:00 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

julia> Pkg.status("ImageCore")
 - ImageCore                     0.3.3
```

**Comment by timholy** [comment]
Hmm, on 0.6.0-rc2 I get this:
```julia
julia> using ImageCore

julia> using Base.Test

julia> detect_ambiguities(ImageCore, Base, Core)
Skipping Base.<|
0-element Array{Tuple{Method,Method},1}

julia> detect_ambiguities(ImageCore, ColorTypes, Base, Core)
Skipping Base.<|
0-element Array{Tuple{Method,Method},1}
```
which leads me to tentatively suggest updating your version of Julia? Of course it's possible that the ambiguity detection isn't working properly, but if so we'll need a test case to debug this.

**Comment by marius311** [comment]
I just tried on 0.6RC2 and while I reproduce your ambiguity tests above, I still see my error. I guess isn't it obvious from the error message above that those two functions are indeed ambiguous for the given argument types? 

I will try to produce a reduced test case but it doesn't seem totally trivial and I don't quite have time now, but here's the stack trace at least. Its coming from inside a Dict generator,

```
MethodError: convert(::Type{Array{Union{},1}}, ::Array{Union{},1}) is ambiguous. Candidates:
  convert(::Type{Array{Cdest,n}}, img::AbstractArray{T,n}) where {Cdest<:(ColorTypes.Colorant{T,1} where T), n, T<:Real} in ImageCore at /home/marius/.julia/v0.6/ImageCore/src/convert_reinterpret.jl:105
  convert(::Type{Array{C,n}}, img::Array{C,n}) where {C<:ColorTypes.Colorant, n} in ImageCore at /home/marius/.julia/v0.6/ImageCore/src/convert_reinterpret.jl:76
Possible fix, define
  convert(::Type{Array{Union{},n}}, ::Array{Union{},n})

Stacktrace:
 [1] grow_to!(::Dict{Any,Any}, ::Base.Generator{Dict{Any,Any},CMBLensing.##320#323}) at ./dict.jl:173
 [2] associative_with_eltype(::Base.##178#180, ::Base.Generator{Dict{Any,Any},CMBLensing.##320#323}, ::Type{T} where T) at ./dict.jl:167
 [3] Dict(::Base.Generator{Dict{Any,Any},CMBLensing.##320#323}) at ./dict.jl:145
 [4] indexed_next(::Base.Generator{Tuple{Symbol,Symbol},CMBLensing.##319#322{Int64,PyCall.PyObject}}, ::Int64, ::Int64) at ./tuple.jl:56
 [5] #class#318(::Int64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::CMBLensing.#class) at /home/marius/.julia/v0.6/CMBLensing/src/cls.jl:29
 [6] (::CMBLensing.#kw##class)(::Array{Any,1}, ::CMBLensing.#class) at ./<missing>:0
```

**Comment by timholy** [comment]
Looking more carefully at your ambiguity, I can see why this happened. We explicitly exclude `Union{}` ambiguities from detection (see https://github.com/JuliaLang/julia/pull/20982) because these don't usually arise in "real" code: `Union{}` represents an empty result from type intersection,
```julia
julia> typeintersect(Float64, Real)
Float64

julia> typeintersect(Float64, Int)
Union{}
```
It's possible that this is actually a Julia bug, or it's possible that whatever code you're using is doing something funny to allocate the element type. Either way, I don't think it makes sense to resolve the ambiguity without more information, because it's a really weird operation to want to support.

**Comment by timholy** [comment]
If it's coming from a comprehension, then https://github.com/JuliaLang/julia/issues/15276 is a possible culprit. (I have that issue number memorized...)

**Comment by marius311** [comment]
Ah bingo, that helped me realize how to reduce the error. Here it is,

```
julia> using ImageCore

julia> d=Dict(:a=>1,:b=>2.)
Dict{Symbol,Any} with 2 entries:
  :a => 1
  :b => 2.0

julia> Dict(k=>v for (k,v) in d)
ERROR: MethodError: convert(::Type{Array{Union{},1}}, ::Array{Union{},1}) is ambiguous. Candidates:
  convert(::Type{Array{Cdest,n}}, img::AbstractArray{T,n}) where {Cdest<:(ColorTypes.Colorant{T,1} where T), n, T<:Real} in ImageCore at /home/marius/.julia/v0.6/ImageCore/src/convert_reinterpret.jl:105
  convert(::Type{Array{C,n}}, img::Array{C,n}) where {C<:ColorTypes.Colorant, n} in ImageCore at /home/marius/.julia/v0.6/ImageCore/src/convert_reinterpret.jl:76
Possible fix, define
  convert(::Type{Array{Union{},n}}, ::Array{Union{},n})
Stacktrace:
 [1] grow_to!(::Dict{Any,Any}, ::Base.Generator{Dict{Symbol,Any},##7#8}) at ./dict.jl:173
 [2] associative_with_eltype(::Base.##178#180, ::Base.Generator{Dict{Symbol,Any},##7#8}, ::Type{T} where T) at ./dict.jl:167
 [3] Dict(::Base.Generator{Dict{Symbol,Any},##7#8}) at ./dict.jl:145
```

Feel free to close this / file a Julia issue or whatever is the appropriate way to proceed. FWIW I've got a workaround so this isn't super critical for me for anything.

**Comment by timholy** [comment]
This is great. Probably the fix should go in Julia rather than here, but I'll leave this open as a reminder until I can get to it.

**Comment by marius311** [comment]
> Probably the fix should go in Julia rather than here

Just ran into this issue again, I think there's something I don't understand. Why isn't this an ImageCore issue? It seems like importing ImageCore breaks dict comprehension in cases like the above example, regardless of if detect_ambiguities worked correctly or not, no? Is there anything that can be done?

**Comment by timholy** [comment]
Because the method we need to add to fix it would be type piracy if it were placed in ImageCore.

**Comment by timholy** [comment]
See https://github.com/JuliaLang/julia/pull/22322 and #41.

**Comment by marius311** [comment]
Thanks for the explanation and fix! I confirm its fixed it for me.
