### ISSUE TITLE
FFTW dependency

### ISSUE THREAD

**Issue by tknopp** [JuliaImages/ImageCore.jl#56]
I think ImageCore should (on the stable branch) not depend on the FFTW package:

```
julia> using Images
INFO: Precompiling module Images.
WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/Users/knopp/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to ImageCore:    
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/Users/knopp/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **

WARNING: --output requested, but no modules defined during run
```

ref https://github.com/JuliaMath/FFTW.jl/issues/45#issuecomment-336661303

**Comment by timholy** [comment]
Just FYI, while this is scary it's not actually a problem. Images should work fine.

Moving code out of Base is pretty fraught.

**Comment by tknopp** [comment]
Yes, ok. But still it is wrong that this package depends on FFTW.jl. Though this is a minor thing I really think that we should avoid pulling things from Julia master into the stable package landscape. I am very satisfied/thankful about all Images packages. But things like this and or the `axes` issue make things more fragil than it needs to be. 

(sorry if this sounds like a complaint, but I maintain software (based on Images/Gtk) that is used by non-programmers and it needs to work, otherwise I need to track down the issue)

**Comment by timholy** [comment]
Fair enough. Can you move `src/functions.jl` to ImageFiltering? Then we can get rid of the dependency here.

**Comment by tknopp** [comment]
While this makes sense, it still does not solve the issue. ImageFiltering should also not depend on `FFTW.jl`. `FFTW.jl` should only be used for 0.7- code.

**Comment by timholy** [comment]
Try wrapping the `using FFTW` in an `if VERSION` check?

**Comment by timholy** [comment]
Since we're now only supporting 0.7 on master, this isn't an issue for future development. Closing as `wontfix`.

**Comment by tknopp** [comment]
eagerly waiting for 0.7 version of Images et al. !!! :-)
