### ISSUE TITLE
Julia gets stuck when `vcat` or `hcat`  images of different types

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageCore.jl#64]
For example, 
```julia
using Images
bits = 8:-1:1
graybar = Gray{N0f8}.(transpose(repeat(range(0,stop=1,length=512),1,50))) # Array{Gray{N0f8},2}

graybars = [(Gray{Normed{UInt8, bit}}.(graybar)) for bit in bits] #Array{Array{T,2} where T,1}
# Array elements are not the same type, so it would be slow
vcat(graybars...) # Uh-oh, just stuck here.
```
RAM usage is normal, CPU usage is 100% for a long-long time until I kill julia.

It didn't throw an error here, indeed if I use `bits = 2:-1:1` this code works fine (except its slow speed).

If I explicitly convert them into the same type, then it goes well,
```julia
using Images
bits = 8:-1:1
graybar = Gray{N0f8}.(transpose(repeat(range(0,stop=1,length=512),1,50))) # Array{Gray{N0f8},2}

# Array elements are the same type, so it would be fast as expected.
graybars = [Gray{N0f8}.(Gray{Normed{UInt8, bit}}.(graybar)) for bit in bits] #Array{Array{Gray{Normed{UInt8,8}},2},1}
vcat(graybars...)  # 0.05s in my machine
```

Also, I've tried `promote(graybars...)` but it throws an `sametype_error`

**Comment by timholy** [comment]
Thanks for the bug report, keep them coming!

My immediate mission is to get ImageView working on 1.0 and then I may tackle this next.

**Comment by johnnychen94** [comment]
Addressed by https://github.com/JuliaMath/FixedPointNumbers.jl/pull/113
