### ISSUE TITLE
How to get Array{UInt8, 3} from a RGB image without data copy

### ISSUE THREAD

**Issue by gzhang8** [JuliaImages/ImageCore.jl#66]
I tried `rawview` and `reinterpret`. They are not returning 'Array' type but other types of 'AbstractArray'

``` julia
using TestImages, Images
img = testimage("lighthouse")

v = channelview(img)
r = rawview(v)
@show typeof(r)

c = copy(r)
@show typeof(c)

m = reinterpret(UInt8, img)
@show typeof(m)
```

```
typeof(r) = MappedArrays.MappedArray{UInt8,3,Base.ReinterpretArray{Normed{UInt8,8},3,RGB{Normed{UInt8,8}},Array{RGB{Normed{UInt8,8}},3}},typeof(reinterpret),getfield(ImageCore, Symbol("##32#33")){Normed{UInt8,8}}}
typeof(c) = Array{UInt8,3}
typeof(m) = Base.ReinterpretArray{UInt8,2,RGB{Normed{UInt8,8}},Array{RGB{Normed{UInt8,8}},2}}
```

It looks https://discourse.julialang.org/t/big-overhead-with-the-new-lazy-reshape-reinterpret/7635/4 that it is not straightforward to do the conversion without data copy. I wonder if it is possible to add support from the ImageCore.

**Comment by johnnychen94** [comment]
If you want `Array{UInt,3}`, just do a copy, otherwise there'll be something more subtle happen...
```julia
using TestImages, Images
img1 = testimage("lighthouse")
v = channelview(img1)
r = rawview(v)
r[:] = zeros(size(r))
img1 # becomes all-black image

img2 = testimage("lighthouse")
v = channelview(img2)
r = rawview(v) |> Array
r[:] = zeros(size(r))
img2 # untouched
```

**Comment by timholy** [comment]
May I first ask why you need it to be an `Array{UInt8, 3}` rather than a generic array? In most circumstances, Julia imposes no penalty for abstractions, so the actual type is irrelevant. (Currently there is [a problem with ReinterpretArray](https://github.com/JuliaLang/julia/issues/28980) but hopefully that will be fixed soon.) One of Julia's greatest strengths is its composability.

In some circumstances there *is* a way to do it involving `unsafe_wrap`, but before going there it's worth asking whether this is simply working around a problem that should be fixed in some other way.

**Comment by gzhang8** [comment]
Thank you @johnnychen94 and  @timholy for your reply.

 I am wrapping some C++ code using CxxWrap. I am thinking of passing an image as an UInt8 array using ArrayRef https://github.com/JuliaInterop/CxxWrap.jl#reference-native-julia-arrays. I did some tests. It seems it doesn't take either the MappedArrays or ReinterpretArray. 

Hi, @barche. Do you think this can be handled from CxxWrap side?

**Comment by timholy** [comment]
Ah, OK. Makes sense. You might want to read the docs on `unsafe_wrap`, then; given that you're working in C++ you won't have any trouble understanding what to do. But can't you directly pass the `Matrix{RGB{N0f8}}` from Julia? In the end it's just a pointer, as far as C/C++ is concerned.

**Comment by gzhang8** [comment]
I see. I will checkout `unsafe_wrap`.  

> But can't you directly pass the `Matrix{RGB{N0f8}}` from Julia? In the end it's just a pointer, as far as C/C++ is concerned.

This looks like a more intuitive way to do it. I need to check more on CxxWrap code. I will post my finding later.

**Comment by gzhang8** [comment]
In case someone is interested in this. Please check out https://github.com/JuliaInterop/CxxWrap.jl/issues/111 for more information.
