### ISSUE TITLE
any default/minimal test coverage on image type?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageCore.jl#72]
The current status of test coverage in JuliaImages packages is not good, part of the reason is we don't have consistent testing coverage types in mind. I want to build some utils to make it standardized.

An inspiration is [testutils in Distributions](https://github.com/JuliaStats/Distributions.jl/blob/4e74c25e72b9caeda6a1c1deb993678de1acf2d2/src/testutils.jl), I've also tried to full cover some commonly used types in my [previous PR]( https://github.com/JuliaImages/ImageTransformations.jl/blob/master/test/resizing.jl#L53-L144). But I don't know if there is any default/minimal test requirement on image type for downstream packages(e.g., `ImageTransformations`) -- at least packages under JuliaImages

Full cover all possible image type is impractical, so my idea is to make sure each downstream package's tests cover all combination of the following `Colorant`s and `Number`s (six in total)

* `Number`
  * `Int64` for `Integer`
  * `Float32` for `AbstractFloat`
  * `N0f8` for `Normed`
* Colorant
  * `Gray` for `AbstractGray`
  * `RGB` for `AbstractRGB`

What's your idea in mind? @timholy

**Comment by timholy** [comment]
If you replace `Int` with `Bool` I think this is a good list. `Int` images are weird because of the possible conflation with 0-255 in other languages.

**Comment by johnnychen94** [comment]
I wrote the following util in recent ImageDistances upgrade, I guess this can be applied to other repos as well? [A use case](https://github.com/JuliaImages/ImageDistances.jl/blob/b3d152af95afaa08b86d3d31f6e29900b0ca8fde/test/metrics.jl)

```julia
julia> function generate_test_types(number_types::AbstractArray{<:DataType}, color_types::AbstractArray{<:UnionAll})
           test_types = map(Iterators.product(number_types, color_types)) do T
               try
                   T[2]{T[1]}
               catch err
                   !isa(err, TypeError) && rethrow(err)
               end
           end
           test_types = filter(x->x != false, test_types)
           if isempty(filter(x->x<:Color3, test_types))
               test_types = [number_types..., test_types...]
           end
           test_types
       end
generate_test_types (generic function with 1 method)

julia> generate_test_types([Bool, N0f8, Float32], [RGB])
2-element Array{Any,1}:
 RGB{Normed{UInt8,8}}
 RGB{Float32}        

julia> generate_test_types([Bool, N0f8, Float32], [RGB, Lab])
3-element Array{Any,1}:
 RGB{Normed{UInt8,8}}
 RGB{Float32}        
 Lab{Float32}        

julia> generate_test_types([Bool, N0f8, Float32], [Gray])
6-element Array{DataType,1}:
 Bool                 
 Normed{UInt8,8}      
 Float32              
 Gray{Bool}           
 Gray{Normed{UInt8,8}}
 Gray{Float32}  
```

**Comment by johnnychen94** [comment]
close this in favor of https://github.com/JuliaImages/juliaimages.github.io/issues/108
