### ISSUE TITLE
Add replacement for old deprecations to document

### ISSUE THREAD

**Issue by aminya** [JuliaImages/ImageCore.jl#83]
I am updating an old package (MatlabCompat) that uses these functions (e.g raw, grayim). I think I found them here after a lot of search: https://github.com/JuliaImages/ImageCore.jl/commit/e808091ba0f774a443e39526329a31665b4d83b0#diff-18d62f68c87f15977a1239fc3ca4ed58
These should be addressed at least in the documentation for developers that are updating old packages.

**Comment by johnnychen94** [comment]
Looks like these functions are deprecated by `Images v0.6`, which introduced a bunch of API changes.

I'm not sure if the following helps:

* For `colorim`/`colordim`, you might refer to `colorview`/`channelview`
* `grayim(img)` --> `gray.(img)`
* `raw` --> `rawview`
* `timedim` --> `ImageAxes`

**Comment by aminya** [comment]
@johnnychen94 Thank you for your answer. This is becoming very complex. Because it is not just some API, and types and element type have changed as well.

In the old module, [here](https://github.com/MatlabCompat/MatlabCompat.jl/blob/5c63ce3029fd372fb63d07d77c74cfae1c377ab1/test/runtests.jl#L27), a grayscale image is defined using grayim and its properties are set:
```jl
# make a test image
array = [0.1 0.001 0 0; 0.1 0.401 0 0; 0.1 0.01 0 0; 0.1 0.901 0 0.6];
img = grayim(array);
properties(img)["IMcs"] = "Gray";
```

[Here in my new module](https://github.com/aminya/MatlabCompat.jl/blob/a18f029f2383aa5cd552f040031d5c1472087c8e/test/runtests.jl#L40) I am trying to define a grayscale image from an array. I have come up with 4 different syntaxes, and I am not sure which one is more common or I should choose,
```jl
array = [0.1 0.001 0 0; 0.1 0.401 0 0; 0.1 0.01 0 0; 0.1 0.901 0 0.6];

# Syntax 1 - Array{Gray}
img1 =Gray.(array);
# calculates a grayscale representation of a color image using the Rec 601 luma. (https://juliaimages.org/latest/function_reference/#Color-conversion-1)
imgMet=ImageMeta(img, time="after noon");
println(typeof(img1)) # gives Array{Gray{Float64},2}

# Syntax 2 - ReinterpretArray
img2 = colorview(Gray, array);
# returns a view of the numeric array A, interpreting successive elements of A as if they were channels of Colorant C. (https://juliaimages.org/latest/function_reference/#ImageCore.colorview)
imgMet=ImageMeta(img2, time="after noon"); # to add ImageMeta
println(typeof(img2)) # gives Base.ReinterpretArray{Gray{Float64},2,Float64,Array{Float64,2}}

# Syntax 3 - ReinterpretArray + ImageMeta
imgMet = ImageMeta(colorview(Gray, array), time="after noon")
# returns an ImageMeta type, which holds both data() with Colorant element type, and properties() (Dict type)
properties(imgMet)["location"] = "university"; # to access and extract properties
img3=data(imgMet); # to access and extract data
println(typeof(img3)) # gives Base.ReinterpretArray{Gray{Float64},2,Float64,Array{Float64,2}}

# Syntax 4 - Array + ImageMeta
# this does not work with this module
imgMet = ImageMeta(array, time="after noon")
# returns an ImageMeta type, which holds both data() but array has Float type instead of Colorant, and properties() (Dict type)
properties(imgMet)["location"] = "university"; # to access and extract properties
img4=data(imgMet); # to access and extract data
println(typeof(img4)) # gives Array{Float64,2}
# this synatx does

img=img1; # choose img syntax
```

With three first syntaxes ``eltype(img) <: Gray`` gives [true](https://github.com/aminya/MatlabCompat.jl/blob/a18f029f2383aa5cd552f040031d5c1472087c8e/src/MatlabCompat/imagetools.jl#L61), but the 4th one is just an array.


Also, replacing ``raw(img)`` simply with ``rawview(img)``[ does not work](https://github.com/aminya/MatlabCompat.jl/blob/a18f029f2383aa5cd552f040031d5c1472087c8e/src/MatlabCompat/imagetools.jl#L67) because of no matching methods.

Thank you very much in advance for your help.

**Comment by johnnychen94** [comment]
@aminya 

In ImageCore, I believe we have reached some consensus (syntax 1) that 

* `AbstractArray{Gray}` and `AbstractArray{<:Number}` are interpreted as gray images by default. (Though only `Normed`, `AbstractFloat` and `Bool` are valid `Number`s.)
* `AbstractArray{RGB}` is interpreted as RGB image, `AbstractArray{Lab}` as Lab image, etc

As far as I know, this design solves many ambiguities we’ve met in other languages, two examples of them are: 

* 3D numerical array is interpreted as 3D gray image instead of 2D color image; AbstractArray{RGB, 2} is the 2D RGB image.
* with the usage of `FixedPointNumbers.N0f8`, we don’t mix the peak values `256` of `UInt8` and `1.0` of `Float64`. Other implementations need a significant amount of additional codes to distinguish these to avoid potential bugs.

For your interest, I’ve recently written a blog explaining the ideas here: https://nextjournal.com/johnnychen94/the-principles-of-imagesjl-part-i

The documentation of `ImageCore` definitely needs updates, please feel free to ask if you have more questions. That could be the resource of documentation though :D

**Comment by timholy** [comment]
Thanks @johnnychen94, and sorry @aminya that real life kept me away.

Just so you know, this *was* addressed: we had more than 1000 lines of code to generate deprecation warnings tutoring developers in how to migrate their code. However, you're so many versions behind that most of the helpful transition code has been stripped away. I highly recommend downloading an old version of Julia (probably 0.6.x), and checking out v0.7 or so of Images and contemporaneous versions of its dependencies. You'll get lots of deprecation warnings for migrating old code. Also, see https://github.com/JuliaImages/Images.jl/blob/master/upgrading_tips.md and https://github.com/JuliaImages/Images.jl/blob/master/NEWS.md.

**Comment by aminya** [comment]
> 
> 
> Thanks @johnnychen94, and sorry @aminya that real life kept me away.
> 
> Just so you know, this _was_ addressed: we had more than 1000 lines of code to generate deprecation warnings tutoring developers in how to migrate their code. However, you're so many versions behind that most of the helpful transition code has been stripped away. I highly recommend downloading an old version of Julia (probably 0.6.x), and checking out v0.7 or so of Images and contemporaneous versions of its dependencies. You'll get lots of deprecation warnings for migrating old code. Also, see https://github.com/JuliaImages/Images.jl/blob/master/upgrading_tips.md and https://github.com/JuliaImages/Images.jl/blob/master/NEWS.md.

Thank you!

Well, not every developer or repository has been updated. I see a lot of them around. 

I did try Julia 0.6 to update some parts of the code using [my forked Femto Cleaner](https://github.com/JuliaComputing/Deprecations.jl is not comprehensive enough.) (last version it runs on). However, Femto cleaner also doesn't do enough job for upgrading the codes. (https://github.com/aminya/MatlabCompat.jl/commit/7f9311d110626e2256ded641f8cafb1c471f0416). Probably because Deprecations.jl is not comprehensive enough.

Fortunately for this case, we decided to write the code from scratch. However, not everyone does that. So its good to make Femto Cleaner.jl running again, and also make a tutorial for upgrading packages. (not only for Images.jl)

**Comment by timholy** [comment]
https://github.com/JuliaImages/ImageCore.jl/issues/83#issuecomment-512942382 describes the right migration strategy. In addition to the links already mentioned, see https://discourse.julialang.org/t/big-changes-in-images-jl-v0-6-0/1786.
