### ISSUE TITLE
consistent `colorview` and `channelview` results for `Color1` and `Color3`

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageCore.jl#97]
The following contents are posted by @ianshmean in slack#image-processing: 

Why does `colorview` for `Gray` return a singular first dimension when `RGB` doesn’t?

```julia
julia> size(colorview(Gray, rand(Float32, 1, 10, 10)))
(1, 10, 10)
julia> size(colorview(RGB, rand(Float32, 3, 10, 10)))
(10, 10)
```

I guess it’s because of this:

```
julia> size(channelview(rand(Gray, 10, 10)))
(10, 10)
julia> size(channelview(rand(RGB, 10, 10)))
(3, 10, 10)
```

But I find it odd that `channelview` for `Gray` acts differently because it only has one channel

**Comment by IanButterworth** [comment]
😂thanks! I'll post here next time :)

**Comment by johnnychen94** [comment]
I re-post it here because it's becoming subtle that if we allow operations such as `*(::Gray, ::RGB)` as https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/109 says.

For example, if we allow `*(::Gray, ::RGB)`, the following inconsistency would be found, and this would surprise the user

```julia
julia> x = rand(Gray, 4, 2)
4×2 Array{Gray{Float64},2} with eltype Gray{Float64}:
 Gray{Float64}(0.321694)  Gray{Float64}(0.733467)
 Gray{Float64}(0.999378)  Gray{Float64}(0.624183)
 Gray{Float64}(0.778671)  Gray{Float64}(0.230848)
 Gray{Float64}(0.440432)  Gray{Float64}(0.228529)

julia> y = rand(RGB, 4, 2)
4×2 Array{RGB{Float64},2} with eltype RGB{Float64}:
 RGB{Float64}(0.968626,0.367133,0.960857)  RGB{Float64}(0.958179,0.547058,0.996787) 
 RGB{Float64}(0.265453,0.414573,0.651202)  RGB{Float64}(0.0269492,0.619244,0.350753)
 RGB{Float64}(0.220294,0.824475,0.695889)  RGB{Float64}(0.360293,0.455531,0.852093) 
 RGB{Float64}(0.239853,0.795472,0.248088)  RGB{Float64}(0.153495,0.282899,0.912939) 

julia> Base.:*(x::Gray, y::RGB) = RGB{N0f8}(x.val * y.r, x.val * y.g, x.val * y.b)

julia> channelview(x.*y)
3×4×2 reinterpret(N0f8, ::Array{RGB{N0f8},3}):
[:, :, 1] =
 0.31   0.267  0.173  0.106
 0.118  0.416  0.643  0.349
 0.31   0.651  0.541  0.11 

[:, :, 2] =
 0.702  0.016  0.082  0.035
 0.4    0.388  0.106  0.063
 0.729  0.22   0.196  0.208

julia> channelview(x) .* channelview(y)
ERROR: DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 4 and 3")
Stacktrace:
 [1] _bcs1 at ./broadcast.jl:490 [inlined]
 [2] _bcs at ./broadcast.jl:484 [inlined]
 [3] broadcast_shape at ./broadcast.jl:478 [inlined]
 [4] combine_axes at ./broadcast.jl:473 [inlined]
 [5] instantiate at ./broadcast.jl:256 [inlined]
 [6] materialize(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(*),Tuple{Base.ReinterpretArray{Float64,2,Gray{Float64},Array{Gray{Float64},2}},Base.ReinterpretArray{Float64,3,RGB{Float64},Array{RGB{Float64},3}}}}) at ./broadcast.jl:819
 [7] top-level scope at REPL[47]:1

julia> reshape(channelview(x), 1, 4, 2) .* channelview(y)
3×4×2 Array{Float64,3}:
[:, :, 1] =
 0.311602  0.265288  0.171537  0.105639
 0.118105  0.414315  0.641995  0.350352
 0.309102  0.650797  0.541869  0.109266

[:, :, 2] =
 0.702793  0.0168212  0.0831728  0.035078 
 0.401249  0.386522   0.105158   0.0646504
 0.731111  0.218934   0.196704   0.208633 
```

What's worse, when `size(x), size(y) == (3, N), (N, M)`, the broadcasting sementics makes it a `(3, N, 1) * (3, N, M)` instead of `(1, 3, N) * (3, N, M)`, a case that should error but actually not. (Imagine the case `N=M=3`)

And this issue would not happen if we make `size(colorview(Gray, rand(Float32, 1, 10, 10))) == (10, 10`.

I think changing the behavior of `colorview` and `channelview` won't affect the core functionality of `Images.jl` since these two functions are mainly used to interact with other packages. And it would be okay as long as we make `colorview`/`channelview` reverse to each other.

**Comment by nlw0** [comment]
I don't agree this is a good idea. You just have to deal with the fact `Gray` is a scalar, and `RGB` a vector. To force `Gray` to create a new dimension with a single point seems way more awkward to me, and way more prone to confuse the user.

**Comment by IanButterworth** [comment]
Perhaps we could add something like `nchannels(::Colorant)` and `nchannels(::AbstractArray{Colorant})` to return the number of channels expected, before `channelview` is done?

BTW, for the most part, I actually like that `channelview(rand(Gray,10,10))` returns a 2D array, it's just when trying to handle converting images of different types to matricies that it gets inelegant

**Comment by IanButterworth** [comment]
Although, should `nchannels(Gray)` return 1 or 0??

**Comment by timholy** [comment]
I remember agonizing over this, and even have the vague impression that it may have changed over time though I can't quickly find evidence of that in the issues/prs history. I've given this issue a 1.0 milestone now, not necessarily to implement but at least to decide. (A bit to busy now to think very carefully.)

**Comment by johnnychen94** [comment]
Hmmm, if we took this propose, since numeric arrays are treated as Gray images, it would surprise developers that `x` is N-D Gray image, while `channelview(x)` is (N+1)-D Gray image. --- But, in cases `channelview` is needed, `Gray` and `RGB` can be processed by the same method; no extra specification needed.

**Comment by johnnychen94** [comment]
If we compare these two usages, both look "normal" while only one of them works:

```julia
julia> x = rand(Gray{Float32}, 4, 4);

julia> y = rand(RGB{Float32}, 4, 4);

julia> channelview(x) + channelview(y)
ERROR: DimensionMismatch("dimensions must match")
Stacktrace:
 [1] promote_shape at .\indices.jl:154 [inlined]
 [2] promote_shape at .\indices.jl:150 [inlined]
 [3] promote_shape(::Base.ReinterpretArray{Float32,2,Gray{Float32},Array{Gray{Float32},2}}, ::Base.ReinterpretArray{Float32,3,RGB{Float32},Array{RGB{Float32},3}}) at .\indices.jl:145
 [4] +(::Base.ReinterpretArray{Float32,2,Gray{Float32},Array{Gray{Float32},2}}, ::Base.ReinterpretArray{Float32,3,RGB{Float32},Array{RGB{Float32},3}}) at .\arraymath.jl:38
 [5] top-level scope at REPL[32]:1

julia> x + y # ColorVectorSpace
4×4 Array{RGB{Float32},2} with eltype RGB{Float32}:
```

**Comment by nlw0** [comment]
I'm sorry, are you sure you're not attaching yourself too strongly to a very personal opinion about what is "normal"? I find the current behavior absolutely fine and desirable. RGB values are intrinsically multi-dimensional, and Gray is scalar. Sticking to the simplest representation when converting to raw arrays is a very good design choice.

What you might call a problem here is the fact we currently support `rand(RGB{Float32}) + Gray{Float32}(10.0)` instead of forcing a `.+` as happens with arrays. I have no idea what is the mechanism currently allowing this implicit conversion, though. Ideally I believe such conversions should not be implicit, and I believe this has been the principle in the library and Julia in general.

I'm sure there's a need to some people to be able to easily handle operations involving both scalar and multidimensional arrays. I just think this should be implemented as something separate and higher-level, on top of this library.

**Comment by johnnychen94** [comment]
> I'm sorry, are you sure you're not attaching yourself too strongly to a very personal opinion about what is "normal"?

The fact is no I am not; I'm contributing use cases and try to find out what legacy/new issues this change may solve/bring. To be honest, given the fact that currently there are few contributors to JuliaImages, approving this change means another set of work to do for us and of course for Tim.

What's more important to me is to figure out what the ideal ImageCore should be like regardless of the current implementation, and add it to the FAQ of documentation when necessary. If we don't propose the change now, then we would less likely to have a chance to do it after `v1.0`.

There would always be a force to stick to what we're familiar with, but familiarity doesn't necessarily mean it's good. The general image processing community was much more familiar with the raw array implementation, but still, we choose to use the current "image pixel is the array element" representation and find it a good practice. 

> we currently support `rand(RGB{Float32}) + Gray{Float32}(10.0)` instead of forcing a .+ as happens with arrays

Actually, "forcing a `.+` as happens with arrays" breaks the "image pixel is the array element" design, allowing this means we're breaking the atomic element, which is the old way of doing image processing, i.e., broadcasting. If we're still reasoning about `Gray`-`RGB` differences, I believe it's because we're not providing enough tools to deal with this abstraction.

> Ideally I believe such conversions should not be implicit, and I believe this has been the principle in the library and Julia in general

This is what we're doing now and it should still be in the future. As I said earlier, I believe these two functions should ideally only serve for external and backward-compatibility usage and they're working just like `save` and `load`. Generally, if you're using these two functions, it means you're still following the "old style", or interacting with other "old-style" functions (e.g., algorithms that only suits the raw arrays, other non-JuliaImages libraries that only support numerical array operations). From the cases, I believe the change I propose here suits the external usage more.

Disclaimer: My thought may or may not be bullshit, and from the records, it's very likely that I disapprove of what I've said here in the future, but reflections and criticizations are needed to ensure so.

**Comment by johnnychen94** [comment]
@Evizero Some insights on this issue? I saw you've made two operations `SplitChannels` and `CombineChannnels` in Augmentor.jl based on `channelview` and `colorview`

**Comment by IanButterworth** [comment]
My vote is for an optional arg to split single channel colors to a singleton dim, and maintain current behavior as default. 

`channelview(img, keepsingletonchannel=true)`

Which defaults to false. 

There might be a shorter arg name, but you get the idea.

**Comment by johnnychen94** [comment]
`keepsingletonchannel` isn't a good idea to me:

* understanding the `keepsingletonchannel` keyword doesn't become easier than the manual `reshape(channelview(x), :, size(x)...)` (Although here `reshape` allocates new memory, do we have something like `reshape_view`?).
* it requires `colorview` to support the same keyword. If users forget to pass that keyword, they'll still be surprised.

**Comment by johnnychen94** [comment]
A second thought. It reminds me that when I use raw numerical data to process images, I would assume the following case: `M*N` => gray, `M*N*3`=>RGB, `M*N*1`=>ERROR. I believe the general community has this model in mind, for example, if we pass a `M*N*1` array to matplotlib, it errors.

```python
# python
>>>plt.imshow(np.random.rand(2, 2, 1))

TypeError: Invalid shape (2, 2, 1) for image data
```

**Comment by johnnychen94** [comment]
I found some old discussion on this issue in Augmentor: https://github.com/Evizero/Augmentor.jl/pull/4#discussion_r122191767

Perhaps what's needed is to document this behavior clearly in a FAQ page

**Comment by timholy** [comment]
It's funny how long it takes to achieve clarity, but https://github.com/JuliaLang/julia/pull/37559 now makes it quite clear that we indeed hit on the *most* consistent solution here in ImageCore, without quite realizing it at the time. That PR introduces  `reinterpret(reshape, T, A)`, and it couldn't be consistent without behaving the way that ImageCore's `reinterpretc` currently behaves. Deciding based on "is it a number or is it a colorant?" makes it seem ambiguous, but as soon as you reduce it to a problem of element sizes it becomes clear that there's only one generic answer.

Whew! One less "if a tree falls..." existential question to worry about.
